2025-07-23 14:26:43,731 - SDKLogger - INFO - initializer - initializer.py - initialize - 130  - Initialization successful for Email Id : gfiacconi@unitedventures.com in Environment : https://www.zohoapis.eu.
2025-07-23 14:26:43,732 - SDKLogger - INFO - initializer - initializer.py - initialize - 130  - Initialization successful for Email Id : gfiacconi@unitedventures.com in Environment : https://www.zohoapis.eu.
2025-07-23 14:26:43,732 - SDKLogger - INFO - initializer - initializer.py - initialize - 130  - Initialization successful for Email Id : gfiacconi@unitedventures.com in Environment : https://www.zohoapis.eu.
2025-07-23 14:26:43,816 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:43,816 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:44,097 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:44,097 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:44,388 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:44,388 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:44,697 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:44,697 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:44,985 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:44,985 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:45,280 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:45,280 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:45,571 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:45,571 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:45,858 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:45,858 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:46,143 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:46,143 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:46,429 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:46,429 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:46,716 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:46,716 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:47,007 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:47,007 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:47,294 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:47,294 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:47,583 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:47,583 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:47,879 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:47,879 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:48,170 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:48,170 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:48,452 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:48,452 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:48,737 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:48,737 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:49,024 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:26:49,024 - SDKLogger - INFO - common_api_handler - common_api_handler.py - api_call - 290  - Exception in authenticating current request : Caused By: INVALID CLIENT ERROR - invalid_code
2025-07-23 14:28:48,037 - SDKLogger - INFO - initializer - initializer.py - initialize - 130  - Initialization successful for Email Id : gfiacconi@unitedventures.com in Environment : https://www.zohoapis.eu.
2025-07-23 14:28:48,038 - SDKLogger - INFO - initializer - initializer.py - initialize - 130  - Initialization successful for Email Id : gfiacconi@unitedventures.com in Environment : https://www.zohoapis.eu.
2025-07-23 14:28:48,038 - SDKLogger - INFO - initializer - initializer.py - initialize - 130  - Initialization successful for Email Id : gfiacconi@unitedventures.com in Environment : https://www.zohoapis.eu.
2025-07-23 14:28:48,044 - SDKLogger - INFO - api_http_connector - api_http_connector.py - fire_request - 100  - POST - URL = https://www.zohoapis.eu/crm/v2/coql , HEADERS = {"Authorization": " ## can't disclose ## ", "X-ZOHO-SDK": "Darwin/24.5.0 python/3.13.4:3.1.0"} , PARAMS = {}.
2025-07-23 14:28:48,044 - SDKLogger - INFO - api_http_connector - api_http_connector.py - fire_request - 100  - POST - URL = https://www.zohoapis.eu/crm/v2/coql , HEADERS = {"Authorization": " ## can't disclose ## ", "X-ZOHO-SDK": "Darwin/24.5.0 python/3.13.4:3.1.0"} , PARAMS = {}.
2025-07-23 14:28:48,624 - SDKLogger - INFO - api_http_connector - api_http_connector.py - fire_request - 100  - POST - URL = https://www.zohoapis.eu/crm/v2/coql , HEADERS = {"Authorization": " ## can't disclose ## ", "X-ZOHO-SDK": "Darwin/24.5.0 python/3.13.4:3.1.0"} , PARAMS = {}.
2025-07-23 14:28:48,624 - SDKLogger - INFO - api_http_connector - api_http_connector.py - fire_request - 100  - POST - URL = https://www.zohoapis.eu/crm/v2/coql , HEADERS = {"Authorization": " ## can't disclose ## ", "X-ZOHO-SDK": "Darwin/24.5.0 python/3.13.4:3.1.0"} , PARAMS = {}.
2025-07-23 14:28:49,132 - SDKLogger - INFO - api_http_connector - api_http_connector.py - fire_request - 100  - POST - URL = https://www.zohoapis.eu/crm/v2/coql , HEADERS = {"Authorization": " ## can't disclose ## ", "X-ZOHO-SDK": "Darwin/24.5.0 python/3.13.4:3.1.0"} , PARAMS = {}.
2025-07-23 14:28:49,132 - SDKLogger - INFO - api_http_connector - api_http_connector.py - fire_request - 100  - POST - URL = https://www.zohoapis.eu/crm/v2/coql , HEADERS = {"Authorization": " ## can't disclose ## ", "X-ZOHO-SDK": "Darwin/24.5.0 python/3.13.4:3.1.0"} , PARAMS = {}.
2025-07-23 14:28:49,655 - SDKLogger - INFO - api_http_connector - api_http_connector.py - fire_request - 100  - POST - URL = https://www.zohoapis.eu/crm/v2/coql , HEADERS = {"Authorization": " ## can't disclose ## ", "X-ZOHO-SDK": "Darwin/24.5.0 python/3.13.4:3.1.0"} , PARAMS = {}.
2025-07-23 14:28:49,655 - SDKLogger - INFO - api_http_connector - api_http_connector.py - fire_request - 100  - POST - URL = https://www.zohoapis.eu/crm/v2/coql , HEADERS = {"Authorization": " ## can't disclose ## ", "X-ZOHO-SDK": "Darwin/24.5.0 python/3.13.4:3.1.0"} , PARAMS = {}.
